name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      AMBERHOME: /usr/share/miniconda

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file env.yml --name base
#   - name: Lint with flake8
#     run: |
#         $CONDA/bin/conda install flake8
#         # stop the build if there are Python syntax errors or undefined names
#         $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Install ties
#      run: |
#        pip install .
    - name: Install pytest
      run: |
        pip install pytest
#    - name: Test with pytest
#      run: |
#        cd testing
#        python3 -m pytest
#    - name: Simple Ligand renaming
#      run: |
#        cd examples/mol2_2ligands_MCL1
#        python3 lig_api.py
#    - name: Use min API
#      run: |
#        cd examples/mol2_2ligands_MCL1
#        python3 min_api.py
#        python3 .test_min_api.py
#    - name: Use API
#      run: |
#        cd examples/mol2_2ligands_MCL1
#        python3 api.py
#    - name: CMD hybrid
#      run: |
#        cd examples/mol2_2ligands_MCL1
#        ties create -l l02.mol2 l03.mol2 -nc -1 -dir cmdties
#    - name: CMD with protein
#      run: |
#        cd examples/mol2_2ligands_MCL1
#        ties create -l l02.mol2 l03.mol2 -nc -1 -dir cmdties_protein -p protein.pdb